PROGRAM = DuetWiFiSocketServer
BUILD_DIR = ../build/

FIRMWARE_DIR = ../Release/
FW_FILE = ../Release/DuetWiFiServer.bin

EXTRA_CXXFLAGS = -std=gnu++11

EXTRA_COMPONENTS = extras/dhcpserver

include ../../esp-open-rtos/common.mk
